spring:
  datasource:
    url: jdbc:mysql://localhost:3306/green_link?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: age0504!
    driver-class-name: com.mysql.cj.jdbc.Driver